### ISSUE TITLE
Bad free from generated if variable names are split in different lines in the fixed form version

### ISSUE THREAD

**Issue by ecasglez** [ylikx/fortran-legacy-tools#2]
Consider the following code, where the name of variable IJKLMN is split in the write statement:

```Fortran
      PROGRAM example
         IMPLICIT NONE
         INTEGER :: IJKLMN
         IJKLMN = 9
         WRITE(*,*) 'This is a very long line',IJKL
     &         MN
      END PROGRAM example
```

Splitting the name of the variables in different lines seems to be valid fixed-form Fortran. After processing the file with fixed2free2.py, the new free-form file is:

```Fortran
PROGRAM example
   IMPLICIT NONE
   INTEGER :: IJKLMN
   IJKLMN = 9
   WRITE(*,*) 'This is a very long line',IJKL &
         MN
END PROGRAM example
```

This causes compilation errors since variables IJKL and MN are not declared. Free-form Fortran does not seem to accept splitting the name of the variables in different lines. In the case that IMPLICIT NONE is omitted, the compiler is expecting a "," or an operator between IJKL and MN.

It also happens with labels. For example spliting the go to 100:

```Fortran
      IF (very long stuff) GO TO 10
     & 0
```

And also happens for things like:

```Fortran
      IF (very long stuff) THE
     & N
```

**Comment by ylikx** [comment]
Yes, this is a limitation of this script. This is related to the fact that in fixed form Fortran whitespace characters are not significant (in the columns for code, outside of string literals), whereas in free form they are.

For example: Instead of
```Fortran
      WRITE (*,*) IJKLMN
```
one could also write:
```Fortran
      WR    IT E (*,   *) I J K       LM N
```

I think for handling this you would need a fairly complete Fortran parser, which is outside the scope of a simple script such as fixed2free2.py
The parser would have to support even the most recent Fortran standard, since fixed form is still allowed.

I will add a note to the readme that this kind of code cannot be handled by the script.
